### ISSUE TITLE
Coexistence with docker CRI?

### ISSUE THREAD

**Issue by micw** [automaticserver/lxe#5]
Hello,
is it possible to run this in coexistence with docker as CRI (probably on the same nodes)?

**Comment by dionysius** [comment]
Yes and No.

No for on same node, because I hardly believe kubelet is designed to only run once per node. It might be possible by overwriting all kubelet arguments, but I think this is not worth the effort and reliability (e.g. resource limits are scoped per kubelet in the end)

**Yes** for coexistence in the cluster! Define your own label for that node (see [kubelet `--node-labels`](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/)) - e.g. `my.example.com/containerruntime=lxc` - that it's running lxe/d/c and you can define a [node affinity to that label](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity) to the pods - e.g.
```
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: my.example.com/containerruntime
            operator: In
            values:
            - lxc
```

But you might want also to [taint that node](https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/), so no docker pods are scheduled onto it (since they won't run)
